import { MockAnswerHistoryRow, MockCompletedAttempt } from "./analyticsTypes";

export const MOCK_COMPLETED_ATTEMPTS: MockCompletedAttempt[] = [
  {
    id: "attempt-1",
    date: "2026-05-26",
    title: "Practice Session A",
    topic: "Analytics",
    correct: 4,
    incorrect: 1,
    unanswered: 0,
    total: 5,
    scorePercent: 80,
  },
  {
    id: "attempt-2",
    date: "2026-05-27",
    title: "Topic Drill - Persistence",
    topic: "Architecture",
    correct: 3,
    incorrect: 1,
    unanswered: 1,
    total: 5,
    scorePercent: 60,
  },
  {
    id: "attempt-3",
    date: "2026-05-28",
    title: "Scoring Rules Review",
    topic: "Scoring",
    correct: 2,
    incorrect: 2,
    unanswered: 1,
    total: 5,
    scorePercent: 40,
  },
  {
    id: "attempt-4",
    date: "2026-05-29",
    title: "Mixed Mock Exam",
    topic: "Import",
    correct: 4,
    incorrect: 0,
    unanswered: 1,
    total: 5,
    scorePercent: 80,
  },
];

export const MOCK_ANSWER_HISTORY: MockAnswerHistoryRow[] = [
  {
    id: "h1",
    attemptId: "attempt-1",
    date: "2026-05-26",
    testTitle: "Practice Session A",
    topic: "Analytics",
    question: "Which metric best represents overall test reliability over time?",
    selectedAnswer: "Average score across completed tests",
    correctAnswer: "Average score across completed tests",
    result: "correct",
  },
  {
    id: "h2",
    attemptId: "attempt-2",
    date: "2026-05-27",
    testTitle: "Topic Drill - Persistence",
    topic: "Architecture",
    question:
      "In local-first architecture, which statement is correct for Testlytic MVP direction?",
    selectedAnswer: "Only aggregate analytics should be stored",
    correctAnswer: "User data should remain on-device unless explicitly exported",
    result: "incorrect",
  },
  {
    id: "h3",
    attemptId: "attempt-2",
    date: "2026-05-27",
    testTitle: "Topic Drill - Persistence",
    topic: "Architecture",
    question: "What is the primary value of topic-level analytics?",
    selectedAnswer: "Unanswered",
    correctAnswer: "Detect strongest and weakest topic performance",
    result: "unanswered",
  },
  {
    id: "h4",
    attemptId: "attempt-3",
    date: "2026-05-28",
    testTitle: "Scoring Rules Review",
    topic: "Scoring",
    question: "If negative marking is enabled, what should happen in scoring?",
    selectedAnswer: "Incorrect answers should apply configured penalty",
    correctAnswer: "Incorrect answers should apply configured penalty",
    result: "correct",
  },
  {
    id: "h5",
    attemptId: "attempt-4",
    date: "2026-05-29",
    testTitle: "Mixed Mock Exam",
    topic: "Import",
    question: "Which import workflow matches the intended Testlytic data flow in docs?",
    selectedAnswer: "JSON -> Validation -> SQLite -> Tests -> Analytics",
    correctAnswer: "JSON -> Validation -> SQLite -> Tests -> Analytics",
    result: "correct",
  },
];
